# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='energymodel',
            name='id_name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
