# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyframework',
            name='basicfactsheet_ptr',
        ),
        migrations.RemoveField(
            model_name='energymodel',
            name='basicfactsheet_ptr',
        ),
        migrations.DeleteModel(
            name='BasicFactsheet',
        ),
        migrations.DeleteModel(
            name='Energyframework',
        ),
        migrations.DeleteModel(
            name='Energymodel',
        ),
    ]
