# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0008_auto_20160301_0051")]

    operations = [
        migrations.AddField(
            model_name="energyscenario",
            name="further_assumptions_for_postprocessing_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="energyscenario",
            name="potential_geothermal_other",
            field=models.BooleanField(default=False, verbose_name="other"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="additional_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Which additional software is required to run the model?",
                    max_length=1000,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="citation_DOI",
            field=models.CharField(
                help_text="publications about the model",
                max_length=10000,
                null=True,
                verbose_name="Citation DOI",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="citation_reference",
            field=models.CharField(
                help_text="publications about the model",
                max_length=10000,
                null=True,
                verbose_name="Citation reference",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="costs",
            field=models.CharField(max_length=1000, null=True, verbose_name="Costs"),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="current_contact_person",
            field=models.CharField(
                help_text="Who is the main contact person?",
                max_length=1000,
                null=True,
                verbose_name="Current contact person",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="data_provided",
            field=models.CharField(
                choices=[("none", "none"), ("some", "some"), ("all", "all")],
                default="none",
                help_text="Is the necessary data to run a scenario available?",
                max_length=1000,
                verbose_name="Data provided",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="documentation_quality",
            field=models.CharField(
                choices=[
                    ("expandable", "expandable"),
                    ("good", "good"),
                    ("excellent", "excellent"),
                ],
                default="expandable",
                help_text="How is the quality of the documentations?",
                max_length=1000,
                verbose_name="Documentation quality",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="external_optimizer_yes_text",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="framework_yes_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="institutions",
            field=models.CharField(
                help_text="Which institutions develop(ed) the model?",
                max_length=1000,
                verbose_name="Institution(s)",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="interal_data_processing_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Which data processing software is required?",
                    max_length=1000,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="larger_scale_usage",
            field=models.CharField(
                help_text="Is this model used on a larger scale? If so, who uses it?",
                max_length=10000,
                null=True,
                verbose_name="Larger scale usage",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="license",
            field=models.CharField(
                choices=[("Apache", "Apache"), ("Other", "Other")],
                default="Apache",
                max_length=1000,
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="license_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="model_name",
            field=models.CharField(
                help_text="What is the full model name?",
                max_length=1000,
                unique=True,
                verbose_name="Model name",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="modelling_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="What modelling software and which version is used?",
                    max_length=1000,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="number_of_devolopers",
            field=models.CharField(
                choices=[
                    ("less than 10", "less than 10"),
                    (" less than 20", " less than 20"),
                    (" less than 50", " less than 50"),
                    (" more than 50", " more than 50"),
                ],
                default="less than 10",
                help_text="How many people are involved in the model development?",
                max_length=1000,
                verbose_name="Number of devolopers",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="number_of_users",
            field=models.CharField(
                choices=[
                    ("less than 10", "less than 10"),
                    (" less than 100", " less than 100"),
                    (" less than 1000", " less than 1000"),
                    (" more than 1000", " more than 1000"),
                ],
                default="less than 10",
                help_text="How many people approximately use the model?",
                max_length=1000,
                verbose_name="Number of users ",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="primary_outputs",
            field=models.CharField(
                help_text="What are the main outputs of the model?",
                max_length=1000,
                null=True,
                verbose_name="Primary Outputs",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="primary_purpose",
            field=models.CharField(
                help_text="What is the primary purpose the model?",
                max_length=1000,
                null=True,
                verbose_name="Primary Purpose",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="references_to_reports_produced_using_the_model",
            field=models.CharField(
                help_text="Which studies have been calculated with this model?",
                max_length=10000,
                null=True,
                verbose_name="References to reports produced using the model",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="model_types_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="used",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                null=True,
                size=None,
                verbose_name="Models using this framework",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="additional_dimensions_sector_ecological_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="additional_dimensions_sector_economic_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="additional_dimensions_sector_others_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="additional_dimensions_sector_social_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="example_research_questions",
            field=models.CharField(
                help_text="What would be a good research question that could be answered with the model?",
                max_length=10000,
                null=True,
                verbose_name="Example research questions",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="geographical_coverage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    default="",
                    help_text="What regions are covered? Please, list the regions covered by the model. Leave blank, if the model and data are not limited to a specific region. Example input: USA, Canada, Mexico",
                    max_length=1000,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="model_class_optimization_LP_MILP_Nonlinear_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="model_class_other_text",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="model_specific_properties",
            field=models.CharField(
                help_text="What are main specific characteristics (strengths and weaknesses) of this model regarding the purpose of the recommendation?",
                max_length=10000,
                null=True,
                verbose_name="Model specific properties",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="short_description_of_mathematical_model_class",
            field=models.CharField(
                max_length=1000,
                null=True,
                verbose_name="Short description of mathematical model class",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="technical_data_anchored_in_the_model",
            field=models.CharField(
                help_text="If there is technical data already embedded (hard code) in the model and not part of the scenario, please make that transparent here.",
                max_length=10000,
                null=True,
                verbose_name="Technical data anchored in the model",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="typical_computation_hardware",
            field=models.CharField(
                help_text="Here you can specify which hardware was assumed to estimate above time (e.g. RAM, CPU, GPU, etc).",
                max_length=10000,
                null=True,
                verbose_name="Typical computation hardware",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="validation",
            field=models.CharField(
                help_text="How is the model validated?",
                max_length=10000,
                null=True,
                verbose_name="Validation",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="aim",
            field=models.CharField(
                help_text="What is the purpose (hypothesis) and research question of the study?",
                max_length=1000,
                null=True,
                verbose_name="Aim",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="author_Institution",
            field=models.CharField(
                help_text="Who are the authors of the study and for which institution do they work?",
                max_length=1000,
                verbose_name="Author, Institution",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="citation_doi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=1000, verbose_name="Citation doi"
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="citation_reference",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=1000, verbose_name="Citation reference"
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="client",
            field=models.CharField(
                help_text="Who are the customers requesting the study?",
                max_length=1000,
                null=True,
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="comparability_Validation",
            field=models.CharField(
                help_text="How far do the modelling results fit in compared to similar scientific research?",
                max_length=1000,
                null=True,
                verbose_name="Comparability / Validation",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="conclusions",
            field=models.CharField(
                help_text="What political, social (or in another way) relevant conclusions are drawn from the scenario analysis? ",
                max_length=1000,
                null=True,
                verbose_name="Conclusions",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="development_of_environmental_aspects",
            field=models.CharField(
                help_text="e.g. landuse",
                max_length=1000,
                null=True,
                verbose_name="Development of environmental aspects",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="ecological_data",
            field=models.CharField(
                help_text="What kind of ecological data(sets) are included / were used? (e.g. landuse, CO2 emissions,...) What were the data(sets) used for (e.g. model calibration)?",
                max_length=1000,
                null=True,
                verbose_name="Ecological data",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="economic_behavioral_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="economic_development",
            field=models.CharField(
                help_text="e.g. price structures, market settings,..",
                max_length=1000,
                null=True,
                verbose_name="Economic development",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="economic_focuses_included",
            field=models.CharField(
                help_text="Have there been economic focusses/sectors included?",
                max_length=1000,
                null=True,
                verbose_name="Economic focuses included",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="economical_data",
            field=models.CharField(
                help_text="What kind of economical data(sets) are included / were used? (e.g. price structures, market settings,...) What were the data(sets) used for (e.g. model calibration)?",
                max_length=1000,
                null=True,
                verbose_name="Economical data",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="emission_reductions_amount",
            field=models.SmallIntegerField(
                help_text="Development of emissions",
                null=True,
                verbose_name="Potential energy saving",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="emission_reductions_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="emission_reductions_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="endogenous_variables",
            field=models.CharField(
                help_text="Which time series and variables are generated inside the model? (Does this question belong into the scenario fact sheet?)",
                max_length=1000,
                null=True,
                verbose_name="Endogenous variables",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="energy_saving_amount",
            field=models.SmallIntegerField(
                help_text="development of energy savings or efficiency",
                null=True,
                verbose_name="Energy saving",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="energy_saving_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="exogenous_time_series_used_others_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="modeled_energy_sectors_others_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="name_of_scenario",
            field=models.CharField(
                help_text="What is the name of the scenario?",
                max_length=1000,
                unique=True,
                verbose_name="Name of the Scenario",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="name_of_the_study",
            field=models.CharField(
                help_text="What is the name of the study?",
                max_length=1000,
                verbose_name="Name of the study",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="new_aspects",
            field=models.CharField(
                help_text="What is new? (beyond state of research)",
                max_length=1000,
                null=True,
                verbose_name="New aspects",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_biomass_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_energy_savings_amount",
            field=models.SmallIntegerField(
                help_text="How was the potential of energy savings determined?",
                null=True,
                verbose_name="Potential energy saving",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_energy_savings_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_energy_savings_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_geothermal_othertext",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_hydro_power_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_solar_electric_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_solar_thermal_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="potential_wind_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="preProcessing",
            field=models.CharField(
                help_text="Have the mentioned values been modified before being used for the modelling exercise or are they used directly? Please, describe what kind of modification have been made? Additionally, you can link to data processing scripts.",
                max_length=1000,
                null=True,
                verbose_name="Pre-Processing",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="renewables_others_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="robustness",
            field=models.CharField(
                help_text="How is the robustness of the results proofed?",
                max_length=1000,
                null=True,
                verbose_name="Robustness",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_heat_amount",
            field=models.SmallIntegerField(
                help_text="development of renewable energy in the heat sector",
                null=True,
                verbose_name="Share RE (heat sector)",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_heat_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_heat_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_mobility_amount",
            field=models.SmallIntegerField(
                help_text="development of renewable energy in the mobility sector",
                null=True,
                verbose_name="Share RE (mobility sector)",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_mobility_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_mobility_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_power_amount",
            field=models.SmallIntegerField(
                help_text="Development of renewable energy in the power sector",
                null=True,
                verbose_name="Share RE (power sector)",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_power_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_power_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_total_amount",
            field=models.SmallIntegerField(
                help_text="development of total renewable energy supply",
                null=True,
                verbose_name="Share RE (total energy supply)",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_total_kind",
            field=models.CharField(
                choices=[
                    ("until", "until"),
                    ("per", "per"),
                    ("not estimated", "not estimated"),
                ],
                default="until",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="share_RE_total_year",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="social_data",
            field=models.CharField(
                help_text="What kind of social data(sets) are included / were used / considered? (e.g. demographic changes, employment rate; social structure, ...) What were the data(sets) used for (e.g. model calibration)?",
                max_length=1000,
                verbose_name="Social data",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="social_developement",
            field=models.CharField(
                help_text="How are changes of social structure considered? (e.g. demographic changes, employment rate, ...)",
                max_length=1000,
                null=True,
                verbose_name="Social developement",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="social_focuses_included",
            field=models.CharField(
                help_text="Have there been social focusses/sectors included? ",
                max_length=1000,
                null=True,
                verbose_name="Social focuses included",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="spatial_Geographical_coverage",
            field=models.CharField(
                help_text="Which geographical region is adressed in the study?",
                max_length=1000,
                null=True,
                verbose_name="Spatial / Geographical coverage",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="technical_data",
            field=models.CharField(
                help_text="What kind of technical data(sets) are included /used? (heat-/powerplants; grid infrastructure;...) What were the data(sets) used for (e.g. model calibration)?",
                max_length=1000,
                null=True,
                verbose_name="Technical data + usage",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="technological_innovations",
            field=models.CharField(
                help_text="Have future technological innovations been regarded?",
                max_length=10000,
                null=True,
                verbose_name="Technological innovations",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="time_frame_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="time_steps_other_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="tools_other",
            field=models.CharField(
                help_text="Which model(s) and other tools have been used?",
                max_length=1000,
                null=True,
                verbose_name="Tools",
            ),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="uncertainty_assessment",
            field=models.CharField(
                help_text="How are the identified uncertain factors considered in the study?",
                max_length=1000,
                null=True,
                verbose_name="Uncertainty assessment",
            ),
        ),
    ]
