"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("modelview", "0011_auto_20160301_1033")]

    operations = [
        migrations.AlterField(
            model_name="energyscenario",
            name="energy_saving_year",
            field=models.SmallIntegerField(null=True),
        )
    ]
