# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0011_auto_20160301_1033")]

    operations = [
        migrations.AlterField(
            model_name="energyscenario",
            name="energy_saving_year",
            field=models.SmallIntegerField(null=True),
        )
    ]
