# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 12:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0012_auto_20160301_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicfactsheet',
            name='external_optimizer_yes_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='energymodel',
            name='model_class_other_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='energymodel',
            name='observation_period_other_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
