"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("modelview", "0019_auto_20160303_2217")]

    operations = [
        migrations.AlterField(
            model_name="energyscenario",
            name="storages_CAES",
            field=models.BooleanField(verbose_name="compressed air"),
        ),
        migrations.AlterField(
            model_name="energyscenario",
            name="storages_PHS",
            field=models.BooleanField(verbose_name="pump hydro"),
        ),
    ]
