# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0022_auto_20160303_2233")]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="number_of_devolopers",
            field=models.CharField(
                choices=[
                    ("less than 10", "less than 10"),
                    (" less than 20", " less than 20"),
                    (" less than 50", " less than 50"),
                    (" more than 50", " more than 50"),
                ],
                help_text="How many people are involved in the model development?",
                max_length=1000,
                null=True,
                verbose_name="Number of devolopers",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="number_of_users",
            field=models.CharField(
                choices=[
                    ("less than 10", "less than 10"),
                    (" less than 100", " less than 100"),
                    (" less than 1000", " less than 1000"),
                    (" more than 1000", " more than 1000"),
                ],
                help_text="How many people approximately use the model?",
                max_length=1000,
                null=True,
                verbose_name="Number of users ",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="primary_outputs",
            field=models.TextField(
                help_text="What are the main outputs of the model?",
                null=True,
                verbose_name="Primary Outputs",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="primary_purpose",
            field=models.TextField(
                help_text="What is the primary purpose the model?",
                null=True,
                verbose_name="Primary Purpose",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="model_types",
            field=models.CharField(
                choices=[
                    ("Grid optimisation", "Grid optimisation"),
                    ("demand simulation", "demand simulation"),
                    ("feed-in simulation", "feed-in simulation"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Mathematical model",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="comment_on_geo_resolution",
            field=models.TextField(
                help_text="Feel free to explain the geographical resolution of the model e.g. with regard to the grid data.",
                null=True,
                verbose_name="Comment on geographic (spatial) resolution",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="model_file_format",
            field=models.CharField(
                choices=[
                    (".exe", ".exe"),
                    (".gms", ".gms"),
                    (".py", ".py"),
                    (".xls", ".xls"),
                    ("Other", "Other"),
                ],
                default="other",
                help_text="In which format is the model saved?",
                max_length=5,
                verbose_name="Model file format",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="model_input",
            field=models.CharField(
                choices=[
                    (".csv", ".csv"),
                    (".py", ".py"),
                    ("text", "text"),
                    (".xls", ".xls"),
                    ("Other", "Other"),
                ],
                default="other",
                help_text="Of which file format are the input and output data?",
                max_length=5,
                verbose_name="Input/output data file format",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="short_description_of_mathematical_model_class",
            field=models.TextField(
                null=True, verbose_name="Short description of mathematical model class"
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="user_behaviour_yes_text",
            field=models.TextField(null=True),
        ),
    ]
