# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0024_auto_20160315_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymodel',
            name='mathematical_objective_other_text',
            field=models.TextField(blank=True),
        ),
    ]
