# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0026_auto_20160315_1447")]

    operations = [
        migrations.AddField(
            model_name="energymodel",
            name="changes_in_efficiency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="network_coverage_NT",
            field=models.BooleanField(
                default=False, verbose_name="net transfer capacities"
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="geographical_coverage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="What regions are covered? Please, list the regions covered by the model. Leave blank, if the model and data are not limited to a specific region. Example input: USA, Canada, Mexico",
                null=True,
                size=None,
                verbose_name="Geographical coverage (comma-separated)",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="market_models",
            field=models.CharField(
                choices=[
                    ("fundamental model", "fundamental model"),
                    ("stochastic model", "stochastic model"),
                ],
                help_text="Which / Is a market models are included?",
                max_length=20,
                null=True,
                verbose_name="Market models",
            ),
        ),
    ]
