# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0029_auto_20160315_1743")]

    operations = [
        migrations.RemoveField(model_name="energyframework", name="model_types"),
        migrations.AddField(
            model_name="energyframework",
            name="model_types_demand_simulation",
            field=models.BooleanField(default=False, verbose_name="demand simulation"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="model_types_feed_in_simulation",
            field=models.BooleanField(default=False, verbose_name="feed-in simulation"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="model_types_grid",
            field=models.BooleanField(default=False, verbose_name="Grid optimisation"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="model_types_other",
            field=models.BooleanField(default=False, verbose_name="Other"),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="changes_in_efficiency",
            field=models.TextField(null=True, verbose_name="Changes in efficiency"),
        ),
    ]
