# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0032_auto_20160323_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyscenario',
            name='networks_electricity_gas_electricity',
            field=models.BooleanField(default=True, verbose_name='electricity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyscenario',
            name='networks_electricity_gas_gas',
            field=models.BooleanField(default=True, verbose_name='gas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicfactsheet',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Logo'),
        ),
    ]
