# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0033_energyframework_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyframework',
            name='test',
        ),
    ]
