# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0033_auto_20160414_1346'),
        ('modelview', '0035_auto_20170724_1801'),
    ]

    operations = [
    ]
