# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Tom Heimbrodt <https://github.com/tom-heimbrodt>
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # ('modelview', '0035_auto_20160426_1721'),
        ("modelview", "0035_auto_20170724_1801")
    ]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="source_of_funding",
            field=models.CharField(
                help_text="What is the main source of funding?",
                max_length=200,
                null=True,
                verbose_name="Source of funding",
            ),
        )
    ]
