# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 18:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0036_basicfactsheet_tags")]

    operations = [
        migrations.AddField(
            model_name="energymodel",
            name="model_class_simulation_bottom_up",
            field=models.BooleanField(default=False, verbose_name="Bottom up"),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="model_class_simulation_top_down",
            field=models.BooleanField(default=False, verbose_name="Top down"),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="properties_missed",
            field=models.CharField(
                help_text="Which properties of your model have not been mentioned on this factsheet? Please nite them.",
                max_length=10000,
                null=True,
                verbose_name="further properties",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="additional_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="Which additional software is required to run the model?",
                null=True,
                size=None,
                verbose_name="Additional software",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                default=list,
                help_text="Who are the authors? Where do / did they work, on which parts of the model, during which time period?",
                null=True,
                size=None,
                verbose_name="Author(s) (institution, working field, active time period)",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="citation_DOI",
            field=models.CharField(
                help_text="If  there are publications about the model that have a DOI please liste the DOIs",
                max_length=10000,
                null=True,
                verbose_name="Citation DOI",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="citation_reference",
            field=models.CharField(
                help_text="Please list publications about the model",
                max_length=10000,
                null=True,
                verbose_name="Citation reference",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="code_documentation",
            field=models.CharField(
                help_text="If a code documentation and or a developer documentation is publicly available please insert the link",
                max_length=200,
                null=True,
                verbose_name="Link to Developer/Code Documentation",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="contact_email",
            field=models.EmailField(
                help_text="Please provide the mailadress of the contact person.",
                max_length=254,
                verbose_name="Contact (e-mail)",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="documentation_quality",
            field=models.CharField(
                choices=[
                    ("not available", "not available"),
                    ("expandable", "expandable"),
                    ("good", "good"),
                    ("excellent", "excellent"),
                ],
                default="expandable",
                help_text="How do you rate the quality of the documentations?",
                max_length=1000,
                verbose_name="Documentation quality",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="external_optimizer",
            field=models.BooleanField(
                default=False,
                help_text="Which external optimizer(s) can the model apply? Please list them.",
                verbose_name="External optimizer",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="institutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="Which institutions develop(ed) the model?",
                null=True,
                size=None,
                verbose_name="Institution(s)",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="interal_data_processing_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="Which data processing software is required? Please list all software (packages) that are used for internal data processing",
                null=True,
                size=None,
                verbose_name="Internal data processing software",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="larger_scale_usage",
            field=models.CharField(
                help_text="Is this model used from various (maybe well known) institutions? If so, who uses it?",
                max_length=10000,
                null=True,
                verbose_name="Larger scale usage",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="logo",
            field=models.ImageField(
                help_text="If a logo for the model exists load it up",
                null=True,
                upload_to="logos",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="modelling_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="Which modelling software and which version is used?",
                size=None,
                verbose_name="Modelling software ",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="primary_purpose",
            field=models.TextField(
                help_text="What is the primary purpose of the model?",
                null=True,
                verbose_name="Primary Purpose",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="references_to_reports_produced_using_the_model",
            field=models.CharField(
                help_text="Which studies have been calculated with this model?",
                max_length=10000,
                null=True,
                verbose_name="Please list references to reports and studies which were produced using the model",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="source_of_funding",
            field=models.CharField(
                help_text="What is the main source of funding for the development of the model?",
                max_length=200,
                null=True,
                verbose_name="Source of funding",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="support",
            field=models.BooleanField(
                default=False,
                help_text="Click the check box if there is a support or Q and A Forum for the Model",
                verbose_name="Support / Community / Forum",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="user_documentation",
            field=models.CharField(
                help_text="If an user documentation is publicly available please insert the link",
                max_length=200,
                null=True,
                verbose_name="Link to User Documentation",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="website",
            field=models.CharField(
                help_text="If a website for the model exists please put the link here",
                max_length=200,
                null=True,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="changes_in_efficiency",
            field=models.TextField(
                help_text="Can changes in efficiency be considered in the model? If yes please shortly explain how that is realised.",
                null=True,
                verbose_name="Changes in efficiency",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="example_research_questions",
            field=models.CharField(
                help_text="Which would be good research questions that could be answered with the model?",
                max_length=10000,
                null=True,
                verbose_name="Example research questions",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="market_models",
            field=models.CharField(
                choices=[
                    ("fundamental model", "fundamental model"),
                    ("stochastic model", "stochastic model"),
                ],
                help_text="If the described model is not a market model itself please indicate if a market model is included - if yes,  which one?",
                max_length=20,
                null=True,
                verbose_name="Market models",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="short_description_of_mathematical_model_class",
            field=models.TextField(
                help_text="Here you can explain little more the model class in your own words if you think that the above categorisation is not explicative enough.",
                null=True,
                verbose_name="Short description of mathematical model class",
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="time_resolution_anual",
            field=models.BooleanField(default=False, verbose_name="annual"),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="user_behaviour",
            field=models.BooleanField(
                default=False,
                help_text="Can user behaviour and demand side management be considered in the model? If yes please shortly explain how that is realised.",
                verbose_name="User behaviour and demand side management",
            ),
        ),
    ]
