# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0037_auto_20171130_1909")]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="energymodel",
            name="properties_missed",
            field=models.TextField(
                help_text="Which properties of your model have not been mentioned on this factsheet? Please nite them.",
                null=True,
                verbose_name="further properties",
            ),
        ),
    ]
