# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0036_merge_20170808_1551'),
        ('modelview', '0038_auto_20171130_1930'),
    ]

    operations = [
    ]
