# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("modelview", "0039_auto_20171211_1228")]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="methodical_focus_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="methodical_focus_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
