# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0040_auto_20171211_1239'),
        ('modelview', '0039_merge_20171201_1118'),
    ]

    operations = [
    ]
