# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("modelview", "0041_merge_20171211_1420")]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="license",
            field=models.CharField(
                choices=[
                    ("MIT Licence", "MIT Licence"),
                    ("Apache Licence", "Apache Licence"),
                    ("GNU GPL Licence", "GNU GPL Licence"),
                    ("Other", "Other"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="License",
            ),
        )
    ]
