# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0042_auto_20171215_0953'),
        ('modelview', '0036_auto_20170322_1622'),
    ]

    operations = [
    ]
