# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-07 14:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelview", "0045_auto_20191007_1511"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicfactsheet",
            name="methodical_focus_1",
        ),
        migrations.RemoveField(
            model_name="basicfactsheet",
            name="methodical_focus_2",
        ),
        migrations.RemoveField(
            model_name="basicfactsheet",
            name="methodical_focus_3",
        ),
        migrations.AddField(
            model_name="basicfactsheet",
            name="contact_phone",
            field=models.CharField(
                help_text="If a website for the model exists please put the link here",
                max_length=200,
                null=True,
                verbose_name="Phone",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Biomass",
            field=models.BooleanField(default=False, verbose_name="Biomass"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Geothermal",
            field=models.BooleanField(default=False, verbose_name="Geothermal"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Hydro",
            field=models.BooleanField(default=False, verbose_name="Hydro"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Solar",
            field=models.BooleanField(default=False, verbose_name="Solar"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Tidal",
            field=models.BooleanField(default=False, verbose_name="Tidal"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Wave",
            field=models.BooleanField(default=False, verbose_name="Wave"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="Wind",
            field=models.BooleanField(default=False, verbose_name="Wind"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="agricultural_demand",
            field=models.BooleanField(
                default=False,
                help_text="Which agricultural demand were already modelled with the framework?",  # noqa
                verbose_name="Agricultural demand",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ap_BottomUp",
            field=models.BooleanField(default=False, verbose_name="Bottom up"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ap_Hybrid",
            field=models.BooleanField(default=False, verbose_name="Hybrid"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ap_Other",
            field=models.BooleanField(default=False, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ap_TopDown",
            field=models.BooleanField(default=False, verbose_name="Top Down"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="auto_model_generator",
            field=models.BooleanField(
                default=False,
                help_text="Is an auto-model generator available that transfers an input file into a model?",  # noqa
                verbose_name="Auto model generator",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="cd_Offices",
            field=models.BooleanField(default=False, verbose_name="Offices"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="cd_Retail",
            field=models.BooleanField(default=False, verbose_name="Retail"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="cd_Warehouses",
            field=models.BooleanField(default=False, verbose_name="Warehouses"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_CO2",
            field=models.BooleanField(default=False, verbose_name="CO2 cost"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_FixedOperation",
            field=models.BooleanField(
                default=False, verbose_name="Fixed Operation & Maintenance"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_FuelHandling",
            field=models.BooleanField(default=False, verbose_name="OFuel handling"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_FuelPrices",
            field=models.BooleanField(default=False, verbose_name="Fuel prices"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_Investment",
            field=models.BooleanField(default=False, verbose_name="Investment"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ci_VariableOperation",
            field=models.BooleanField(
                default=False, verbose_name="Variable Operation & Maintenance"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="data_code_availability",
            field=models.CharField(
                help_text="Is at least one (dummy) data set available to run a model built with the framework",  # noqa
                max_length=200,
                null=True,
                verbose_name="Data availability",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="data_postprocessing",
            field=models.BooleanField(
                default=False,
                help_text="Are there any scripts for data post-processing (e.g. calculating demand, economic functions)",  # noqa
                verbose_name="data postprocessing",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="data_preprocessing",
            field=models.BooleanField(
                default=False,
                help_text="Are there any scripts for data pre-processing (e.g. calculating demand, economic functions)",  # noqa
                verbose_name="data preprocessing",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_aviation",
            field=models.BooleanField(default=False, verbose_name="Aviation"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_battery",
            field=models.BooleanField(
                default=False, verbose_name="Battery-electric vehicles"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_combustion",
            field=models.BooleanField(
                default=False, verbose_name="Internal-combustion vehicles"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_hydrogen",
            field=models.BooleanField(default=False, verbose_name="Hydrogen vehicles"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_rail",
            field=models.BooleanField(default=False, verbose_name="Rail"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="dc_v2grid",
            field=models.BooleanField(
                default=False, verbose_name="Vehicle-to-grid electric vehicles"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="es_CPLEX",
            field=models.BooleanField(default=False, verbose_name="CPLEX"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="es_Coin",
            field=models.BooleanField(default=False, verbose_name="Coin-Or CBC"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="es_GLPK",
            field=models.BooleanField(default=False, verbose_name="GLPK"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="es_Gurobi",
            field=models.BooleanField(default=False, verbose_name="Gurobi"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="es_MOSEK",
            field=models.BooleanField(default=False, verbose_name="MOSEK"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="fixed_units",
            field=models.BooleanField(
                default=False,
                help_text="Is the framework build on fixed base units?",
                verbose_name="Fixed units",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="fw_appliance",
            field=models.CharField(
                help_text="Which research projects (on-going or past) apply the framework?",  # noqa
                max_length=1000,
                null=True,
                verbose_name="Projects using the framework",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gm_LinearOptimal",
            field=models.BooleanField(
                default=False, verbose_name="Linear optimal power flow"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gm_TranshipmentModel",
            field=models.BooleanField(default=False, verbose_name="Transhipment model"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gm_singleNode",
            field=models.BooleanField(default=False, verbose_name="Single-node modeL"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gps_backcast",
            field=models.BooleanField(default=False, verbose_name="Back casting"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gps_explore",
            field=models.BooleanField(default=False, verbose_name="Exploring"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gps_forecast",
            field=models.BooleanField(default=False, verbose_name="Forecasting"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gs_global",
            field=models.BooleanField(default=False, verbose_name="Global"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gs_local",
            field=models.BooleanField(default=False, verbose_name="Local/community"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gs_national",
            field=models.BooleanField(default=False, verbose_name="National"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gs_regional",
            field=models.BooleanField(default=False, verbose_name="Regional"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="gs_single_project",
            field=models.BooleanField(
                default=False, verbose_name="Points/degree of abstraction"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="how_to_cite",
            field=models.CharField(
                help_text="How to cite the framework?",
                max_length=1000,
                null=True,
                verbose_name="Citation",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_CSV",
            field=models.BooleanField(default=False, verbose_name="CSV"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_GAMS",
            field=models.BooleanField(
                default=False, verbose_name="GAMS data exchange format (gdx)"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_Pandas",
            field=models.BooleanField(
                default=False, verbose_name="Pandas DataFrame/Series"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_Plots",
            field=models.BooleanField(default=False, verbose_name=" Plots (png, pdf)"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_Python_dicts",
            field=models.BooleanField(default=False, verbose_name="Python dicts"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_XLSX",
            field=models.BooleanField(default=False, verbose_name="XLSX"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_XML",
            field=models.BooleanField(default=False, verbose_name="XML"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_db",
            field=models.BooleanField(default=False, verbose_name="db"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="idf_txt",
            field=models.BooleanField(default=False, verbose_name="txt"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="inital_purpose",
            field=models.CharField(
                help_text="What was the initial purpose/task/motivation to start the development?",  # noqa
                max_length=1000,
                null=True,
                verbose_name="Inital purpose",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="inital_purpose_change",
            field=models.CharField(
                help_text="Did that initial purpose change over time? If yes, what was the intentional purpose?",  # noqa
                max_length=1000,
                null=True,
                verbose_name="Inital purpose change",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="inital_release_date",
            field=models.CharField(
                help_text="When [mm-yyyy] was the framework initially released?",
                max_length=30,
                null=True,
                verbose_name="Inital Release Date",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="installation_guide",
            field=models.BooleanField(
                default=False,
                help_text="Is an installation guide provided for the framework (e.g. as part of the documentation)?",  # noqa
                verbose_name="Installation guide",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="interfaces",
            field=models.CharField(
                help_text="Which interfaces to recommended, additional,  useful software is provided by the framework? Please list! ",  # noqa
                max_length=200,
                null=True,
                verbose_name="interfaces",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="last_updated",
            field=models.CharField(
                help_text="When was the factsheet last updated?",
                max_length=200,
                null=True,
                verbose_name="Last updated",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="link_to_code_documentation",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Link to code documentation"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_abp",
            field=models.BooleanField(
                default=False, verbose_name="Agent based programming"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_dp",
            field=models.BooleanField(
                default=False, verbose_name="Dynamic Programming"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_fl",
            field=models.BooleanField(default=False, verbose_name="Fuzzy Logic"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_lp",
            field=models.BooleanField(default=False, verbose_name="Linear Programming"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_mip",
            field=models.BooleanField(
                default=False, verbose_name="Mixed integer programming"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="new_components",
            field=models.BooleanField(
                default=False,
                help_text="Is the framework build to allow for the implementation of new components?",  # noqa
                verbose_name="New components",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_CSV",
            field=models.BooleanField(default=False, verbose_name="CSV"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_GAMS",
            field=models.BooleanField(
                default=False, verbose_name="GAMS data exchange format (gdx)"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_Pandas",
            field=models.BooleanField(
                default=False, verbose_name="Pandas DataFrame/Series"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_Plots",
            field=models.BooleanField(default=False, verbose_name=" Plots (png, pdf)"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_Python_dicts",
            field=models.BooleanField(default=False, verbose_name="Python dicts"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_XLSX",
            field=models.BooleanField(default=False, verbose_name="XLSX"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_XML",
            field=models.BooleanField(default=False, verbose_name="XML"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_db",
            field=models.BooleanField(default=False, verbose_name="db"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_txt",
            field=models.BooleanField(default=False, verbose_name="txt"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="oft_mce",
            field=models.BooleanField(
                default=False, verbose_name="Minimize CO2-emissions"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="oft_mlce",
            field=models.BooleanField(
                default=False, verbose_name="Minimizing Levelized Cost of Energy"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="oft_msw",
            field=models.BooleanField(
                default=False, verbose_name="Maximize Social Welfare"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="oft_mtsc",
            field=models.BooleanField(
                default=False, verbose_name="Minimize Total System Cost"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="open_to_developers",
            field=models.BooleanField(
                default=False,
                help_text="Is it possible to join the developer group?",
                verbose_name="Open to developers",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="parent_framework",
            field=models.CharField(
                help_text="Is the framework based on a framework? If yes, which?",
                max_length=80,
                null=True,
                verbose_name="Parent Framework",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_C",
            field=models.BooleanField(default=False, verbose_name="C++"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Fortran",
            field=models.BooleanField(default=False, verbose_name="Fortran"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_GAMS",
            field=models.BooleanField(default=False, verbose_name="GAMS"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_GNU",
            field=models.BooleanField(default=False, verbose_name="GNU MathProg"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Java",
            field=models.BooleanField(default=False, verbose_name="Java"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Matlab",
            field=models.BooleanField(default=False, verbose_name="Matlab"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Modelica",
            field=models.BooleanField(default=False, verbose_name="Modelica"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_PHP",
            field=models.BooleanField(default=False, verbose_name="PHP"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Python",
            field=models.BooleanField(default=False, verbose_name="Python"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_R",
            field=models.BooleanField(default=False, verbose_name="R"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_Ruby",
            field=models.BooleanField(default=False, verbose_name="Ruby"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="pf_VBA",
            field=models.BooleanField(default=False, verbose_name="MS Excel / VBA"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="plotting_functionalities",
            field=models.BooleanField(
                default=False,
                help_text="Are specific plotting functionalities available?",
                verbose_name="plotting functionalities",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="rd_ApplianceUsage",
            field=models.BooleanField(default=False, verbose_name="Appliance usage"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="rd_Cooking",
            field=models.BooleanField(default=False, verbose_name="Cooking"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="rd_Heating",
            field=models.BooleanField(default=False, verbose_name="Heating"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="rd_Lighting",
            field=models.BooleanField(default=False, verbose_name="Lighting"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="rd_SmartAppliances",
            field=models.BooleanField(
                default=False, verbose_name="Smart appliances & Smart metres"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="research_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                help_text="What are 3 typical research questions that are answered by applying the FW?",  # noqa
                null=True,
                size=None,
                verbose_name="Research questions",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="skills_advanced",
            field=models.CharField(
                help_text="What advanced skills does a person need to become a user of the framework?",  # noqa
                max_length=200,
                null=True,
                verbose_name="Skills advanced",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="skills_basic",
            field=models.CharField(
                help_text="What basic skills does a person need to become a user of the framework?",  # noqa
                max_length=200,
                null=True,
                verbose_name="Skills basic",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="source_code_availability",
            field=models.CharField(
                help_text="What is the link to the source code? If left empty, field won't appear.",  # noqa
                max_length=200,
                null=True,
                verbose_name="Code availability",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_appraisal",
            field=models.BooleanField(default=False, verbose_name="Appraisal"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_capacity_expansion",
            field=models.BooleanField(
                default=False, verbose_name="Capacity expansion planning"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_energy_dispatch",
            field=models.BooleanField(default=False, verbose_name="Energy dispatch"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_energydemand",
            field=models.BooleanField(default=False, verbose_name="Energy demand"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_energysupply",
            field=models.BooleanField(default=False, verbose_name="Energy supply"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_environmental",
            field=models.BooleanField(default=False, verbose_name="Environmental"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_impacts",
            field=models.BooleanField(default=False, verbose_name="Impacts"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_integrated_approach",
            field=models.BooleanField(
                default=False, verbose_name="Integrated approach"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_modular_buildup",
            field=models.BooleanField(default=False, verbose_name="Modular build-up"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_rule_based",
            field=models.BooleanField(
                default=False, verbose_name="Rule based operation management"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_sector_coupling",
            field=models.BooleanField(default=False, verbose_name="Sector-coupling "),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="sps_unit_commitment",
            field=models.BooleanField(default=False, verbose_name="Unit commitment"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_electricity",
            field=models.BooleanField(default=False, verbose_name="Electricity"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_heat",
            field=models.BooleanField(default=False, verbose_name="Heat/Cooling"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_other",
            field=models.BooleanField(
                default=False, verbose_name="Other specific sectors"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_overall",
            field=models.BooleanField(default=False, verbose_name="Overall economy"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_transport",
            field=models.BooleanField(default=False, verbose_name="Transport"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="st_air",
            field=models.BooleanField(
                default=False, verbose_name="Compressed-air energy storage"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="st_battery",
            field=models.BooleanField(
                default=False, verbose_name="Battery energy storage"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="st_hydro",
            field=models.BooleanField(
                default=False, verbose_name="Pumped-hydro energy storage"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="st_hydrogen",
            field=models.BooleanField(
                default=False,
                verbose_name="Hydrogen production / storage / consumption",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_community",
            field=models.BooleanField(default=False, verbose_name="Community"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_forum",
            field=models.BooleanField(default=False, verbose_name="Forum"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_mail",
            field=models.BooleanField(default=False, verbose_name="Mail"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_modelExamples",
            field=models.BooleanField(default=False, verbose_name="Model Examples"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_workshop",
            field=models.BooleanField(default=False, verbose_name="Workshop"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="th_lt",
            field=models.BooleanField(default=False, verbose_name="long term (>=15)"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="th_mt",
            field=models.BooleanField(
                default=False, verbose_name="medium term (>5-<15)"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="th_st",
            field=models.BooleanField(
                default=False, verbose_name="Short term (<= 5 years)"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ts_FiveYearly",
            field=models.BooleanField(default=False, verbose_name="Five-yearly"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ts_Hourly",
            field=models.BooleanField(default=False, verbose_name="Hourly"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ts_Minutely",
            field=models.BooleanField(default=False, verbose_name="Minutely"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ts_Monthly",
            field=models.BooleanField(default=False, verbose_name="Monthly"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ts_Yearly",
            field=models.BooleanField(default=False, verbose_name="Yearly"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_Accounting",
            field=models.BooleanField(default=False, verbose_name="Accounting"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_bc",
            field=models.BooleanField(default=False, verbose_name="Back casting"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_econometric",
            field=models.BooleanField(default=False, verbose_name="Econometric"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_ee",
            field=models.BooleanField(
                default=False, verbose_name="Economic Equilibrium"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_gis",
            field=models.BooleanField(default=False, verbose_name="Spatial (GIS)"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_mc",
            field=models.BooleanField(default=False, verbose_name="Multi-Criteria"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_me",
            field=models.BooleanField(default=False, verbose_name="Macro-Economic"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_optimization",
            field=models.BooleanField(default=False, verbose_name="Optimization"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_simulation",
            field=models.BooleanField(default=False, verbose_name="Simulation"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_st",
            field=models.BooleanField(
                default=False, verbose_name="Spreadsheet/Toolbox"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_stochastic",
            field=models.BooleanField(
                default=False, verbose_name="Stochastic/Monte-Carlo"
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="variable_rolling_horizon",
            field=models.BooleanField(
                default=False,
                help_text="Is it possible to model a variable Rolling Horizon with the framework? ",  # noqa
                verbose_name="Variable rolling",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="variable_time_step",
            field=models.BooleanField(
                default=False,
                help_text="Is it possible to model variable time steps with the framework? ",  # noqa
                verbose_name="Variable time step",
            ),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="version",
            field=models.CharField(
                help_text="To which version of the framework does the factsheet refer?",
                max_length=200,
                null=True,
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="methodical_focus_1",
            field=models.CharField(
                help_text='1-3 Keyords describing the main methodical focus of the model e.g."open source", "sector coupling"',  # noqa
                max_length=50,
                null=True,
                verbose_name="Methodical Focus",
            ),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="methodical_focus_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="energymodel",
            name="methodical_focus_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="acronym",
            field=models.CharField(
                help_text="What is the abbreviation?",
                max_length=20,
                null=True,
                verbose_name="Acronym",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="cooperative_programming",
            field=models.BooleanField(
                default=False,
                help_text="Is it possible to join the coding group?",
                verbose_name="Collaborative programming",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="data_provided",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("example data", "example data"),
                    ("all data", "all data"),
                ],
                default="none",
                help_text="Is the necessary data to run a scenario available?",
                max_length=1000,
                verbose_name="Data provided",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="documentation_quality",
            field=models.CharField(
                choices=[
                    ("not available", "not available"),
                    ("expandable", "expandable"),
                    ("good", "good"),
                    ("excellent", "excellent"),
                ],
                default="expandable",
                help_text="How do you rate the quality of the documentations?",
                max_length=1000,
                null=True,
                verbose_name="Documentation quality",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="external_optimizer",
            field=models.BooleanField(
                default=False,
                help_text="Which external optimizer(s) can the model apply (e.g. Pyomo)? Please list them.",  # noqa
                verbose_name="External optimizer",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="license",
            field=models.CharField(
                choices=[
                    ("Academic Free License v3.0", "Academic Free License v3.0"),
                    ("Apache license 2.0", "Apache license 2.0"),
                    ("Artistic license 2.0", "Artistic license 2.0"),
                    ("Boost Software License 1.0", "Boost Software License 1.0"),
                    (
                        'BSD 2-clause "Simplified" license',
                        'BSD 2-clause "Simplified" license',
                    ),
                    ("BSD 3-clause Clear license", "BSD 3-clause Clear license"),
                    (
                        "Creative Commons license family",
                        "Creative Commons license family",
                    ),
                    (
                        "Creative Commons Zero v1.0 Universal",
                        "Creative Commons Zero v1.0 Universal",
                    ),
                    (
                        "Creative Commons Attribution 4.0",
                        "Creative Commons Attribution 4.0",
                    ),
                    (
                        "Creative Commons Attribution Share Alike 4.0",
                        "Creative Commons Attribution Share Alike 4.0",
                    ),
                    (
                        "Do What The F*ck You Want To Public License",
                        "Do What The F*ck You Want To Public License",
                    ),
                    (
                        "Educational Community License v2.0",
                        "Educational Community License v2.0",
                    ),
                    ("Eclipse Public License 1.0", "Eclipse Public License 1.0"),
                    (
                        "European Union Public License 1.1",
                        "European Union Public License 1.1",
                    ),
                    (
                        "GNU Affero General Public License v3.0",
                        "GNU Affero General Public License v3.0",
                    ),
                    (
                        "GNU General Public License family",
                        "GNU General Public License family",
                    ),
                    (
                        "GNU General Public License v2.0",
                        "GNU General Public License v2.0",
                    ),
                    (
                        "GNU General Public License v3.0",
                        "GNU General Public License v3.0",
                    ),
                    (
                        "GNU Lesser General Public License family",
                        "GNU Lesser General Public License family",
                    ),
                    (
                        "GNU Lesser General Public License v2.1",
                        "GNU Lesser General Public License v2.1",
                    ),
                    (
                        "GNU Lesser General Public License v3.0",
                        "GNU Lesser General Public License v3.0",
                    ),
                    ("ISC", "ISC"),
                    (
                        "LaTeX Project Public License v1.3c",
                        "LaTeX Project Public License v1.3c",
                    ),
                    ("Microsoft Public License", "Microsoft Public License"),
                    ("MIT", "MIT"),
                    ("Mozilla Public License 2.0", "Mozilla Public License 2.0"),
                    ("Open Software License 3.0", "Open Software License 3.0"),
                    ("PostgreSQL License", "PostgreSQL License"),
                    ("SIL Open Font License 1.1", "SIL Open Font License 1.1"),
                    (
                        "University of Illinois/NCSA Open Source License",
                        "University of Illinois/NCSA Open Source License",
                    ),
                    ("The Unlicense", "The Unlicense"),
                    ("zLib License", "zLib License"),
                    ("Other", "Other"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="modelling_software",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                default=list,
                help_text="Which modelling software and which version is used?",
                null=True,
                size=None,
                verbose_name="Modelling software ",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="number_of_devolopers",
            field=models.CharField(
                choices=[
                    ("less than 10", "less than 10"),
                    (" less than 20", " less than 20"),
                    (" less than 50", " less than 50"),
                    (" more than 50", " more than 50"),
                ],
                help_text="How many people are involved in the model development?",
                max_length=1000,
                null=True,
                verbose_name="Number of developers",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="references_to_reports_produced_using_the_model",
            field=models.CharField(
                help_text="Which studies have been calculated with this model?",
                max_length=10000,
                null=True,
                verbose_name="Reference Studies/Models",
            ),
        ),
    ]
