# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.0.4 on 2020-03-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelview", "0048_auto_20191218_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energystudy",
            name="tools_models",
            field=models.ForeignKey(
                help_text="Which model(s) and other tools have been used?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="modelview.Energymodel",
                verbose_name="Tools",
            ),
        ),
    ]
