# Generated by Django 3.0 on 2020-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelview", "0051_auto_20200407_1842"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energyframework",
            name="data_postprocessing",
        ),
        migrations.AddField(
            model_name="energyframework",
            name="data_postprocessing_other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ma_other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="odf_other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="oft_other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="ss_other_text",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="support_other_text",
            field=models.CharField(max_length=1000, null=True, verbose_name="Other"),
        ),
        migrations.AddField(
            model_name="energyframework",
            name="um_other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="license",
            field=models.CharField(
                choices=[
                    ("Academic Free License v3.0", "Academic Free License v3.0"),
                    ("Apache license 2.0", "Apache license 2.0"),
                    ("Artistic license 2.0", "Artistic license 2.0"),
                    ("Boost Software License 1.0", "Boost Software License 1.0"),
                    (
                        'BSD 2-clause "Simplified" license',
                        'BSD 2-clause "Simplified" license',
                    ),
                    ("BSD 3-clause Clear license", "BSD 3-clause Clear license"),
                    (
                        "Creative Commons license family",
                        "Creative Commons license family",
                    ),
                    (
                        "Creative Commons Zero v1.0 Universal",
                        "Creative Commons Zero v1.0 Universal",
                    ),
                    (
                        "Creative Commons Attribution 4.0",
                        "Creative Commons Attribution 4.0",
                    ),
                    (
                        "Creative Commons Attribution Share Alike 4.0",
                        "Creative Commons Attribution Share Alike 4.0",
                    ),
                    (
                        "Do What The F*ck You Want To Public License",
                        "Do What The F*ck You Want To Public License",
                    ),
                    (
                        "Educational Community License v2.0",
                        "Educational Community License v2.0",
                    ),
                    ("Eclipse Public License 1.0", "Eclipse Public License 1.0"),
                    (
                        "European Union Public License 1.1",
                        "European Union Public License 1.1",
                    ),
                    (
                        "GNU Affero General Public License v3.0",
                        "GNU Affero General Public License v3.0",
                    ),
                    (
                        "GNU General Public License family",
                        "GNU General Public License family",
                    ),
                    (
                        "GNU General Public License v2.0",
                        "GNU General Public License v2.0",
                    ),
                    (
                        "GNU General Public License v3.0",
                        "GNU General Public License v3.0",
                    ),
                    (
                        "GNU Lesser General Public License family",
                        "GNU Lesser General Public License family",
                    ),
                    (
                        "GNU Lesser General Public License v2.1",
                        "GNU Lesser General Public License v2.1",
                    ),
                    (
                        "GNU Lesser General Public License v3.0",
                        "GNU Lesser General Public License v3.0",
                    ),
                    ("ISC", "ISC"),
                    (
                        "LaTeX Project Public License v1.3c",
                        "LaTeX Project Public License v1.3c",
                    ),
                    ("Microsoft Public License", "Microsoft Public License"),
                    ("MIT", "MIT"),
                    ("Mozilla Public License 2.0", "Mozilla Public License 2.0"),
                    ("Open Software License 3.0", "Open Software License 3.0"),
                    ("PostgreSQL License", "PostgreSQL License"),
                    ("SIL Open Font License 1.1", "SIL Open Font License 1.1"),
                    (
                        "University of Illinois/NCSA Open Source License",
                        "University of Illinois/NCSA Open Source License",
                    ),
                    ("The Unlicense", "The Unlicense"),
                    ("zLib License", "zLib License"),
                    (
                        "BSD 3-clause 'New' or 'Revised' license",
                        "BSD 3-clause 'New' or 'Revised' license",
                    ),
                    ("Other", "Other"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                help_text="Under which license is the framework published?",
                max_length=50,
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="support",
            field=models.BooleanField(
                default=False,
                help_text="What kind of support is available? Please check the boxes!",
                verbose_name="Support / Community / Forum",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="user_documentation",
            field=models.CharField(
                help_text="Is an user documentation available for the framework? Please insert the link",
                max_length=200,
                null=True,
                verbose_name="Link to User Documentation",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="data_code_availability",
            field=models.CharField(
                help_text="Is at least one (dummy) data set available to run a model built with the framework?",
                max_length=200,
                null=True,
                verbose_name="Data availability",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="installation_guide",
            field=models.BooleanField(
                default=False,
                help_text="Is an installation guide provided for the framework (e.g. as part of the documentation)? Please provide a link",
                verbose_name="Installation guide",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="link_to_code_documentation",
            field=models.CharField(
                help_text="Is a code/API documentation availaibe for the framework? Please insert the link!",
                max_length=200,
                null=True,
                verbose_name="Link to code documentation",
            ),
        ),
        migrations.AlterField(
            model_name="energyframework",
            name="source_code_availability",
            field=models.CharField(
                help_text="What is the link to the source code?",
                max_length=200,
                null=True,
                verbose_name="Code availability",
            ),
        ),
    ]
