"""
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.0 on 2020-09-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelview", "0055_auto_20200908_2126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyframework",
            name="ap_Other",
            field=models.CharField(max_length=400, null=True, verbose_name="Other"),
        ),
    ]
