# Generated by Django 3.0 on 2020-09-16 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0056_auto_20200910_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicfactsheet',
            name='contact_email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), help_text='Please provide the mailadress of the contact person.', size=None, verbose_name='Contact (e-mail)'),
        ),
    ]
