# SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.5 on 2021-08-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelview", "0058_auto_20210112_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyframework",
            name="link_to_installation_guide",
            field=models.CharField(
                help_text="Is an installation guide availaibe for the framework? Please insert the link!",  # noqa
                max_length=200,
                null=True,
                verbose_name="Link to installation guide",
            ),
        ),
    ]
