# Generated by Django 3.2.22 on 2023-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelview", "0059_energyframework_link_to_installation_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicfactsheet",
            name="citation_DOI",
            field=models.CharField(
                help_text="If  there are publications about the model that have a DOI please list the DOIs",
                max_length=10000,
                null=True,
                verbose_name="Citation DOI",
            ),
        ),
        migrations.AlterField(
            model_name="basicfactsheet",
            name="link_to_source_code",
            field=models.CharField(
                help_text="Is the source code to install and run a model available? If possible please provide a link to GitHub e.g. 'https://github.com/OpenEnergyPlatform/oeplatform'. You are free to provide a link to other sources then GitHub.",
                max_length=200,
                null=True,
                verbose_name="Access to source code",
            ),
        ),
    ]
