# Generated by Django 3.2.22 on 2023-10-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelview', '0060_auto_20231016_1624'),
        ('modelview', '0060_auto_20231018_1642'),
    ]

    operations = [
    ]
