# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 07:56
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(max_length=1000)),
                ("schema", models.CharField(max_length=1000)),
                ("revision", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_accessed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        )
    ]
