# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0002_tablerevision_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerevision',
            name='file',
        ),
    ]
