# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 10:49
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0004_auto_20160803_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
