# SPDX-FileCopyrightText: 2016 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("dataedit", "0005_tag_color")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
