# SPDX-FileCopyrightText: 2016 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("dataedit", "0006_auto_20160825_1027")]

    operations = [
        migrations.AlterUniqueTogether(name="schema", unique_together=set([("name",)])),
        migrations.AlterUniqueTogether(
            name="table", unique_together=set([("schema", "name")])
        ),
    ]
