# SPDX-FileCopyrightText: 2017 Tom Heimbrodt <tom-heimbrodt>
# SPDX-FileCopyrightText: 2019 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT


# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("dataedit", "0008_view")]

    operations = [
        migrations.AddField(
            model_name="view",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="view", name="data", field=models.CharField(max_length=3000)
        ),
    ]
