# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dataedit", "0008_auto_20170504_1651")]

    operations = [
        migrations.AddField(
            model_name="tablerevision",
            name="path",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        )
    ]
