# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0009_tablerevision_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerevision',
            name='path',
            field=models.CharField(max_length=1000),
        ),
    ]
