# SPDX-FileCopyrightText: 2017 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("dataedit", "0010_auto_20170504_1753")]

    operations = [
        migrations.AddField(
            model_name="tablerevision",
            name="size",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        )
    ]
