"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("dataedit", "0010_auto_20170504_1753")]

    operations = [
        migrations.AddField(
            model_name="tablerevision",
            name="size",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        )
    ]
