# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0011_tablerevision_size'),
        ('dataedit', '0009_auto_20170404_1222'),
    ]

    operations = [
    ]
