# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0013_auto_20170810_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=1000)),
                ('schema', models.CharField(max_length=1000)),
                ('column_x', models.CharField(max_length=200)),
                ('column_y', models.CharField(max_length=200)),
                ('filters_x', models.CharField(max_length=1000)),
                ('filters_y', models.CharField(max_length=1000)),
            ],
        ),
    ]
