# SPDX-FileCopyrightText: 2020 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2022 Christian Winger <wingechr>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.0.4 on 2020-10-30 09:42

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0013_auto_20170810_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
        ),
    ]
