# Generated by Django 3.0.4 on 2020-04-22 09:51

import colorfield.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0013_auto_20170810_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
