# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 3.0.4 on 2020-10-30 09:42

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0013_auto_20170810_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
        ),
    ]
