# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.0.4 on 2020-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0014_auto_20201103_2037"),
        ("dataedit", "0014_auto_20201030_1042"),
    ]

    operations = []
