# Generated by Django 3.0.4 on 2020-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0014_auto_20201103_2037'),
        ('dataedit', '0014_auto_20201030_1042'),
    ]

    operations = [
    ]
