# SPDX-FileCopyrightText: 2020 Martin Glauer <MGlauer>
# SPDX-FileCopyrightText: 2022 Christian Winger <wingechr>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.0.4 on 2020-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0014_auto_20201103_2037"),
        ("dataedit", "0014_auto_20201030_1042"),
    ]

    operations = []
