# Generated by Django 3.2.5 on 2021-08-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0015_merge_20201106_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
