# Generated by Django 3.2 on 2022-01-28 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0016_auto_20210809_1543"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablerevision",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, max_length=1000
            ),
        ),
    ]
