# SPDX-FileCopyrightText: 2022 Christian Winger <wingechr>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.2 on 2022-01-28 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0016_auto_20210809_1543"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablerevision",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, max_length=1000
            ),
        ),
    ]
