# SPDX-FileCopyrightText: 2022 Christian Winger <wingechr>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.13 on 2022-06-07 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0017_alter_tablerevision_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schema",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="table",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
