"""
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.2.15 on 2022-09-08 20:23

from django.db import migrations, models


def migrate_metadata(apps, schema_editor):
    # Need this ti avoide migration error if database is created from scratch
    pass


def migrate_metadata_rev(apps, schema_editor):
    """no reverse required"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0018_auto_20220607_1829"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="oemetadata",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(migrate_metadata, migrate_metadata_rev),
    ]
