# Generated by Django 3.2.7 on 2022-10-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0019_table_oemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='oemetadata',
        ),
    ]
