# Generated by Django 3.2.4 on 2023-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0019_table_oemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=1000)),
                ('schema', models.CharField(max_length=1000)),
                ('in_progress', models.BooleanField()),
                ('review', models.JSONField(null=True)),
            ],
        ),
    ]
