# Generated by Django 3.2 on 2023-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0020_tablerevision_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablerevision',
            old_name='author',
            new_name='user',
        ),
    ]
