# Generated by Django 3.2.7 on 2022-10-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0020_remove_table_oemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='oemetadata',
            field=models.JSONField(null=True),
        ),
    ]
