# SPDX-FileCopyrightText: 2023 Stephan Uller <steull>
# SPDX-FileCopyrightText: 2024 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.4 on 2023-01-20 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0020_peerreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="peerreview",
            old_name="in_progress",
            new_name="is_finished",
        ),
    ]
