# Generated by Django 3.2 on 2023-03-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataedit', '0022_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerevision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
