# Generated by Django 3.2.13 on 2023-04-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0023_auto_20230414_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
