# Generated by Django 3.2.13 on 2023-04-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0024_alter_peerreview_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='date_finished',
            field=models.DateTimeField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='date_submitted',
            field=models.DateTimeField(default=None, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='PeerReviewManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reviewer', models.CharField(choices=[('contributor', 'CONTRIBUTOR'), ('reviewer', 'REVIEWER')], default='contributor', max_length=20)),
                ('status', models.CharField(choices=[('SAVED', 'SAVED'), ('SUBMITTED', 'SUBMITTED'), ('FINISHED', 'FINISHED')], default='SAVED', max_length=10)),
                ('is_open_since', models.DateTimeField(null=True)),
                ('next_review', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_review', to='dataedit.peerreview')),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_id', to='dataedit.peerreview')),
                ('prev_review', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_review', to='dataedit.peerreview')),
            ],
        ),
    ]
