# Generated by Django 3.2.15 on 2023-05-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0020_alter_table_unique_together'),
        ('dataedit', '0027_alter_peerreviewmanager_is_open_since'),
    ]

    operations = [
    ]
