# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI>
# SPDX-FileCopyrightText: 2025 user <https://github.com/Darynarli>
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.19 on 2023-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0029_alter_peerreviewmanager_current_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerreview",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
