# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 user <https://github.com/Darynarli> © Reiner Lemoine Institut
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.19 on 2023-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0030_peerreview_is_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peerreview",
            name="is_publish",
        ),
        migrations.AddField(
            model_name="table",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
