# SPDX-FileCopyrightText: 2023 Jonas Huber <jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.22 on 2023-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0031_auto_20231204_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="is_publish",
            field=models.BooleanField(default=False),
        ),
    ]
