"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.2.22 on 2023-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0031_auto_20231204_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="is_publish",
            field=models.BooleanField(default=False),
        ),
    ]
