# Generated by Django 3.2.22 on 2024-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0032_alter_table_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='oemetadata',
            field=models.JSONField(null=True),
        ),
    ]
