# Generated by Django 3.2.19 on 2024-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0032_alter_table_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='embargo_time',
            field=models.BooleanField(default=False),
        ),
    ]
