"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.2.22 on 2024-04-11 11:23

from django.db import migrations, models, transaction

from dataedit.models import Table


def add_human_readable_table_name_if_exists_in_oemetadata(apps, schema_editor):
    TableModel: Table = apps.get_model("dataedit", "Table")
    with transaction.atomic():
        for table in TableModel.objects.all():
            table_title = table.get_readable_table_name()

            if table_title:
                table.human_readable_name = table_title
                table.save()


def migrate_table_readable_name_rev(apps, schema_editor):
    """no reverse required"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0033_peerreview_oemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="human_readable_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RunPython(
            add_human_readable_table_name_if_exists_in_oemetadata,
            migrate_table_readable_name_rev,
        ),
    ]
