# Generated by Django 3.2.22 on 2024-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0033_peerreview_oemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='human_readable_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
