# Generated by Django 3.2.22 on 2024-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0033_peerreview_oemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='oemetadata',
            field=models.JSONField(default=None),
        ),
    ]
