# Generated by Django 3.2.19 on 2024-01-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0034_embargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='embargo_time',
        ),
    ]
