# Generated by Django 5.1.4 on 2025-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0037_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="topics",
            field=models.ManyToManyField(related_name="tables", to="dataedit.topic"),
        ),
    ]
