# SPDX-FileCopyrightText: 2025 Christian Winger
#
# SPDX-License-Identifier: AGPL-3.0-or-later


# Generated by Django 5.1.4 on 2025-10-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataedit", "0038_alter_table_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="schema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataedit.schema",
            ),
        ),
    ]
