# Generated by Django 5.1.4 on 2025-10-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0040_tag_table_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="schema",
        ),
    ]
