# Generated by Django 5.1.4 on 2025-10-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0041_remove_table_schema"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schema",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="tablerevision",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="view",
            name="schema",
        ),
    ]
