# Generated by Django 5.1.15 on 2026-01-26 10:58
__license__ = """
SPDX-FileCopyrightText: Christian Winger
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

import logging

from django.db import migrations
from django.db.models import Count, Max

logger = logging.getLogger("oeplatform")


def remove_duplicate_views(apps, schema_editor):
    """remove duplicates of (table, type, name).

    But keep last instance
    """

    View = apps.get_model("dataedit", "View")

    duplicate_groups = (
        View.objects.values("table", "type", "name")  # group by
        .annotate(keep_id=Max("id"), count=Count("id"))
        .filter(count__gt=1)
    )

    for d in duplicate_groups:
        for view in View.objects.filter(
            table=d["table"],
            type=d["type"],
            name=d["name"],
        ).exclude(id=d["keep_id"]):
            logging.warning(f"removing view: {view}")
            view.delete()


def remove_duplicate_views_reverse(apps, schema_editor):
    # do nothing
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("dataedit", "0045_alter_embargo_table"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_views, remove_duplicate_views_reverse),
        migrations.AlterUniqueTogether(
            name="view",
            unique_together={("table", "type", "name")},
        ),
    ]
