# Generated by Django 5.1.4 on 2026-06-18 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0045_alter_embargo_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contributor", "CONTRIBUTOR"),
                            ("reviewer", "REVIEWER"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SAVED", "SAVED"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("FINISHED", "FINISHED"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field_reviews", models.JSONField(default=list)),
                ("sets_finished", models.BooleanField(default=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="dataedit.peerreview",
                    ),
                ),
            ],
            options={
                "ordering": ["opr", "sequence"],
                "unique_together": {("opr", "sequence")},
            },
        ),
    ]
