"""
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.4 on 2026-06-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0047_backfill_reviewrounds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peerreviewmanager",
            name="next_review",
        ),
        migrations.RemoveField(
            model_name="peerreviewmanager",
            name="prev_review",
        ),
    ]
