"""
SPDX-FileCopyrightText: 2026 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.4 on 2026-07-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0048_drop_manager_prev_next_fks"),
        ("dataedit", "0048_strip_stored_dataset_resources"),
    ]

    operations = []
