# Generated by Django 5.1.15 on 2026-07-03 20:56
"""
SPDX-FileCopyrightText: 2026 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0050_dataset_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkLoadEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("validation-error", "Validation error"),
                            ("copy-error", "Copy error"),
                            ("embargo", "Embargo"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("bytes_received", models.BigIntegerField(default=0)),
                ("row_count", models.BigIntegerField(blank=True, null=True)),
                ("id_min", models.BigIntegerField(blank=True, null=True)),
                ("id_max", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_load_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
