# Generated by Django 5.1.15 on 2026-07-04 09:11
"""
SPDX-FileCopyrightText: 2026 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0051_bulkloadevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkloadevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("validation-error", "Validation error"),
                    ("copy-error", "Copy error"),
                    ("embargo", "Embargo"),
                    ("size-cap", "Size cap exceeded"),
                    ("error", "Error"),
                ],
                max_length=32,
            ),
        ),
    ]
