__license__ = """
SPDX-FileCopyrightText: 2026 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.4 on 2026-10-02 14:35
#
# A nullable column with no default: every existing Table reads NULL ("not
# computed yet") until `manage.py recompute_publish_gate --apply` runs on the
# deploy. Checked with sqlmigrate: one ADD COLUMN, no DEFAULT, no UPDATE.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0054_view_unique_table_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="publishable",
            field=models.BooleanField(null=True),
        ),
    ]
