__license__ = """
SPDX-FileCopyrightText: 2026 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.4 on 2026-10-02 18:11
#
# Two nullable columns with no default and never auto_now: every existing
# Table reads NULL ("no change recorded") until a write stamps it. Checked
# with sqlmigrate: two ADD COLUMN ... NULL, no DEFAULT, no UPDATE. The data
# half is backfilled by a separate command (#2558); the metadata half cannot
# be, because nothing ever recorded it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0055_table_publishable"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="data_modified",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="metadata_modified",
            field=models.DateTimeField(null=True),
        ),
    ]
