# Project
site_name: Open Energy Platform Documentation
site_url:
site_description: The Open Energy Platform is the Frontend of the Open Energy Family and specifically provides a Webapplication which is documented using mkdocs.

# Repository
repo_name: OpenEnergyFamily/oeplatform
repo_url: https://github.com/OpenEnergyPlatform/oeplatform
docs_dir: docs

# Configuration
theme:
  name: material
  logo:
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - content.tabs.link

# extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: "#"

plugins:
- search:
- mkdocstrings:

# Customization
extra:
  generator: false
  version:
    provider: mike

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - installation/index.md
    - Installation Guide: installation/guides/installation-docker-dev.md
    - Development setup: installation/guides/development-setup.md
    - Manual Installation Guide: installation/guides/installation.md
  - Development:
    - dev/index.md

    - Best Practices:
      - Software development process: 
        - dev/index.md
      - Frontend and UI:
        - Workflow: dev/frontend/workflow.md
        - Design System: dev/frontend/design-system.md
        - Accessibility: dev/frontend/accessibility.md
    - Context:
      - dev/context.md
  - Documentation:
    - oeplatform-code/index.md
    - Architecture:
      - oeplatform-code/architecture/index.md
      - Infrastructure: oeplatform-code/architecture/infrastructure.md
      - Software Project: oeplatform-code/architecture/project-structure.md
      - oeplatform Modules: oeplatform-code/architecture/modules.md
    - Web-API's:
      - oeplatform-code/web-api/index.md
      - OEDB REST-API:
        - oeplatform-code/web-api/oedb-rest-api/index.md
        # - Draft open-API schema: oeplatform-code/web-api/oedb-rest-api/swagger-ui.html
      - OEKG API:
        - oeplatform-code/web-api/oekg-api/index.md
        - Edit scenario datasets: oeplatform-code/web-api/oekg-api/scenario-dataset.md
    - Features:
      - oeplatform-code/features/index.md
      - 🚧 OEP-Datasets:
        - oeplatform-code/features/oep-datasets/datasets.md
        - oeplatform-code/features/oep-datasets/tech-stack.md
      - 🚧🔄 Upload-Wizard:
        - oeplatform-code/features/upload-wizard/tabular-data-upload.md
      - metaBuilder (Metadata creation):
        - oeplatform-code/features/metaBuilder/index.md
      - 🚧 Open Peer Review:
        - oeplatform-code/features/open-peer-review-process/index.md
        - Technical docs: oeplatform-code/features/open-peer-review-process/technical-docs.md
      - Scenario Bundles:
        - oeplatform-code/features/scenario-bundles/index.md
