# Project
site_name: Open Energy Platform Documentation
site_url:
site_description: The Open Energy Platform is the Frontend of the Open Energy Family and specifically provides a Webapplication which is documented using mkdocs.

# Repository
repo_name: OpenEnergyFamily/oeplatform
repo_url: https://github.com/OpenEnergyPlatform/oeplatform
docs_dir: docs

# Configuration
theme:
  name: material
  logo:
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - content.tabs.link

# extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: "#"

plugins:
- search:
- mkdocstrings:

# Customization
extra:
  generator: false
  version:
    provider: mike

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Development:
    - dev/index.md
    - Context:
      - Use Cases: dev/use-case.md
      - Users: dev/personas.md
    - Best Practices:
      - dev/best-practice.md
      - Design System:
        - dev/design-system/design-system.md
        - Accessibility: dev/design-system/accessibility.md
    - Collaboration:
      - Community: dev/community.md
      - Git & GitHub: dev/git-github.md
    #   - Users: development/collaboration/users.md
      - Planning & Communication: dev/collaboration/planning-communication.md
      - Code of Conduct: dev/collaboration/code-of-conduct.md
      - License and Citation: dev/collaboration/license-and-citation.md
  # - Git:
  #   - development/git/index.md
  #   - Gitignore: development/git/gitignore.md
  #   - Pre-commit: development/git/pre-commit.md
    # - Continuous Integration:
    #   - development/continuous-integration/index.md
    #   - Test-Driven-Development: development/best-practice/test-driven-development-workflow.md
    # - Documentation:
    #   - development/documentation/index.md
    # - Release:
    #   - development/release/index.md
  - Installation & Code Documentation:
    - install-and-documentation/index.md
    - Installation:
      - Installation Guide: install-and-documentation/install/installation.md
      - Manual database setup: install-and-documentation/install/manual-db-setup.md
      - Development setup: install-and-documentation/install/development-setup.md
    - Documentation:
      - Architecture:
        - install-and-documentation/oeplatform-code/architecture/index.md
        - Infrastructure: install-and-documentation/oeplatform-code/architecture/infrastructure.md
        - Software Project: install-and-documentation/oeplatform-code/architecture/project-structure.md
        - oeplatform Modules: install-and-documentation/oeplatform-code/architecture/modules.md
      - Web-API's:
        - install-and-documentation/oeplatform-code/web-api/index.md
        - OEDB REST-API:
          - install-and-documentation/oeplatform-code/web-api/oedb-rest-api/index.md
          # - Draft open-API schema: install-and-documentation/oeplatform-code/web-api/oedb-rest-api/swagger-ui.html
        - OEKG API:
          - install-and-documentation/oeplatform-code/web-api/oekg-api/index.md
      - Features:
        - install-and-documentation/oeplatform-code/features/index.md
        - metaBuilder Metadata creation: install-and-documentation/oeplatform-code/features/metaBuilder/index.md
        - Open Peer Review Process:
          - install-and-documentation/oeplatform-code/features/open-peer-review-process/index.md
          - Technical docs: install-and-documentation/oeplatform-code/features/open-peer-review-process/technical-docs.md
        - Scenario Bundles: install-and-documentation/oeplatform-code/features/scenario-bundles/index.md
