# Project
site_name: Open Energy Platform Documentation
site_url: 
site_description: The Open Energy Platform is the Frontend of the Open Energy Family and specifically provides a Webapplication which is documented using mkdocs.

# Repository
repo_name: OpenEnergyFamily/oeplatform
repo_url: https://github.com/OpenEnergyPlatform/oeplatform
docs_dir: docs

# Configuration
theme:
  name: material
  logo: 
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share

# extensions 
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: "#"

plugins:
- search:
- mkdocstrings:

# Customization
extra:
  generator: false
  version:
    provider: mike

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Installation & Setup: 
    - Installation Guide: install/installation.md
    - Manual database setup: install/manual_db_setup.md
  - Developement & Collaboration: dev/developement.md
  - Code Documentation: 
    - oeplatform-code/index.md
    - Architecture:
      - oeplatform-code/architecture/index.md
    - Application Programming Interface:
      - oeplatform-code/api/index.md
