# SPDX-FileCopyrightText: 2025 Vismaya Jochem <https://github.com/vismayajochem> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform v0.5.0 <https://github.com/rl-institut/oeplatform>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "oeplatform"
SPDX-PackageSupplier = "Jonas Huber <https://github.com/jh-RLI"
SPDX-PackageDownloadLocation = "https://github.com/rl-institut/oeplatform"
SPDX-PackageComment = "AGPL-3.0-or-later"

#[[annotations]]
#path = "docs/**"
#precedence = "override"
#SPDX-FileCopyrightText = ["2023 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut", "2024 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut", "super-repo <https://github.com/rl-institut/super-repo>"]
#SPDX-License-Identifier = "CC-BY-4.0"
#SPDX-FileComment = "Copyright: super-repo documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

#[[annotations]]
#path = ".github/pull_request_template.md"
#precedence = "override"
#SPDX-FileCopyrightText = ["2023 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut", "super-repo <https://github.com/rl-institut/super-repo>"]
#SPDX-License-Identifier = "CC0-1.0"

