# SPDX-FileCopyrightText: 2025 Vismaya Jochem <https://github.com/vismayajochem> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: oeplatform v0.5.0 <https://github.com/rl-institut/oeplatform>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "oeplatform"
SPDX-PackageSupplier = "Jonas Huber <https://github.com/jh-RLI"
SPDX-PackageDownloadLocation = "https://github.com/rl-institut/oeplatform"
SPDX-PackageComment = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = ["2016 Martin Glauer <MGlauer>",
  "2017 Johann Wagner <johannwagner>",
  "2018 Christian Winger <wingechr>",
  "2020 Jonas Huber <@jh-RLI> © Reiner Lemoine Institut",
  "2020 Christian Hofmann <christian-rli> © Reiner Lemoine Institut",
  "2022 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut",
  "2023 Adel Memariani <adelmemariani>",
  "2023 Daryna <Darynarli> © Reiner Lemoine Institut",
  "2023 Stephen Bosch <pajot>",
  "2024 Eike Broda <ebroda>",
  "2024 Bryan Lancien <bmlancien>",
  "oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/img/**"
precedence = "override"
SPDX-FileCopyrightText = ["2017 Marco Finkendei <MFinkendei>",
  "2019 Johann Wagner <johannwagner>",
  "2020 Martin Glauer <MGlauer>",
  "2020 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut",
  "2022 Christian Winger <wingechr>",
  "2024 Bryan Lancien <bmlancien>",
  "2024 Christian Hofmann <christian-rli> © Reiner Lemoine Institut",
  "oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]

path = "base/static/logos/**"
precedence = "override"
SPDX-FileCopyrightText = ["2017 Martin Glauer <MGlauer>",
  "2020 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut",
  "2022 Jonas Huber <@jh-RLI> © Reiner Lemoine Institut",
  "2024 Christian Hofmann <christian-rli> © Reiner Lemoine Institut",
  "2024 Santosh Mutyala <smutyala1at>",
  "oeplatform <https://github.com/OpenEnergyPlatform/oeplatform/>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/OEP_logo_2_no_text.svg"
precedence = "override"
SPDX-FileCopyrightText = ["2017 Martin Glauer <MGlauer>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/OEP_logo_2.png"
precedence = "override"
SPDX-FileCopyrightText = ["2017 Martin Glauer <MGlauer>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/oeplogo.svg"
precedence = "override"
SPDX-FileCopyrightText = ["2019 Johann Wagner <johannwagner>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/open_ego_logo_breit.png"
precedence = "override"
SPDX-FileCopyrightText = ["2017 Martin Glauer <MGlauer>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/OpenEnergyFamily_Logo_OpenEnergyPlatform_untitled_white.svg"
SPDX-FileCopyrightText = ["2021 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/OpenEnergyFamily_Logo_OpenEnergyPlatform.png"
SPDX-FileCopyrightText = ["2021 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/OpenEnergyFamily_Logo_OpenEnergyPlatform.svg"
SPDX-FileCopyrightText = ["2021 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"

[[annotations]]
path = "base/static/project_detail_pages_content/**"
SPDX-FileCopyrightText = ["2022 Jonas Huber <@jh-RLI> © Reiner Lemoine Institut",
  "2022 Maja Zimmermann <mjazimm>",
  "2022 Ludwig Hülk <@Ludee> © Reiner Lemoine Institut",
  "2022 Christian Winger <wingechr>",
  "2024 Eike Broda <ebroda>"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Copyright: OEMetadata documentation © Reiner Lemoine Institut licensed CC-BY-4.0"


#[[annotations]]
#path = ".github/pull_request_template.md"
#precedence = "override"
#SPDX-FileCopyrightText = ["2023 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut", "super-repo <https://github.com/rl-institut/super-repo>"]
#SPDX-License-Identifier = "CC0-1.0"

