# Generated by Django 3.2.18 on 2023-03-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20201109_1559"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedImages",
        ),
    ]
