"""
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.2.18 on 2023-03-09 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20201109_1559"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedImages",
        ),
    ]
