# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160228_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuser',
            new_name='OepUser',
        ),
    ]
