# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160805_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OepUser',
            new_name='myuser',
        ),
    ]
