# SPDX-FileCopyrightText: 2025 Jonas Huber <jonas.huber@rl-institut.de>
# SPDX-FileCopyrightText: 2025 Martin Glauer <martinglauer89@gmail.com>
# SPDX-FileCopyrightText: 2025 Martin Glauer <martinglauer89@googlemail.com>
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("login", "0004_auto_20160907_1938")]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="affiliation",
            field=models.CharField(max_length=50, null=True),
        )
    ]
