# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI>
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer>
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("login", "0008_auto_20170714_1641")]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="description",
            field=models.TextField(default=""),
        )
    ]
