# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_usergroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
