# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_usergroup_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='did_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set([('user', 'group')]),
        ),
    ]
