# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20171120_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
