# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_myuser_is_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
