# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20181018_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
