# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("login", "0016_auto_20181018_1401")]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_native",
            field=models.BooleanField(default=True),
        )
    ]
