# Generated by Django 3.0.4 on 2020-04-21 13:03

import django.contrib.auth.models
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190304_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_md_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
