"""
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-FileCopyrightText: 2025 Johann Wagner <https://github.com/johannwagner>  © Otto-von-Guericke-Universität Magdeburg
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.0.4 on 2020-11-03 19:37

import django.contrib.auth.models
from django.db import migrations

import login.models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0018_auto_20190304_1306"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("objects", login.models.OEPUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usergroup",
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
