# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 08:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models
from oeplatform.settings import METADATA_PERM_GROUP
from login.models import UserGroup

def add_md_group(*args, **kwargs):
    group = UserGroup(name=METADATA_PERM_GROUP)
    group.save()

def add_md_group_rev(*args, **kwargs):
    group = UserGroup.objects.get(name=METADATA_PERM_GROUP)
    group.delete()

class Migration(migrations.Migration):

    dependencies = [("login", "0018_auto_20190304_1306")]

    operations = [
        migrations.RunPython(add_md_group, reverse_code=add_md_group_rev)
    ]