# Generated by Django 3.0.4 on 2020-11-03 19:37

import django.contrib.auth.models
from django.db import migrations

import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0018_auto_20190304_1306"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("objects", login.models.OEPUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usergroup",
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
