# Generated by Django 3.2.18 on 2023-04-18 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0019_auto_20201103_2037"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="myuser",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="facebook",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="linkedin",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="twitter",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="work",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
