# Generated by Django 3.2.18 on 2023-04-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0020_myuser_profile_img_squashed_0032_auto_20230320_1542"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser", old_name="username", new_name="fullname"
        ),
        migrations.AlterField(
            model_name="myuser",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Username"),
        ),
    ]
