"""
SPDX-FileCopyrightText: Christian Winger
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.13 on 2025-11-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0045_alter_embargo_table"),
        ("login", "0022_alter_grouppermission_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppermission",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="dataedit.table",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="dataedit.table",
            ),
        ),
    ]
