# Generated by Django 5.1.15 on 2026-03-05 13:20

from django.db import migrations


def copy_groups_to_organizations(apps, schema_editor):
    UserGroup = apps.get_model("login", "UserGroup")
    Organization = apps.get_model("login", "Organization")
    GroupPermission = apps.get_model("login", "GroupPermission")
    OrganizationPermission = apps.get_model("login", "OrganizationPermission")
    GroupMembership = apps.get_model("login", "GroupMembership")
    OrganizationMembership = apps.get_model("login", "OrganizationMembership")

    for ug in UserGroup.objects.all():
        org, _ = Organization.objects.get_or_create(
            description=ug.description,
            is_admin=ug.is_admin,
        )
        # Copy permissions
        for gp in GroupPermission.objects.filter(holder=ug):
            OrganizationPermission.objects.get_or_create(
                holder=org,
                table=gp.table,
                level=gp.level,
            )

        # Copy memberships
        for gm in GroupMembership.objects.filter(group=ug):
            OrganizationMembership.objects.get_or_create(
                user=gm.user,
                organization=org,
                level=gm.level,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0024_organization_alter_groupmembership_user_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_groups_to_organizations, migrations.RunPython.noop),
    ]
