"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-05 13:20

from django.db import migrations


def copy_groups_to_organizations(apps, schema_editor):
    UserGroup = apps.get_model("login", "UserGroup")
    Organization = apps.get_model("login", "Organization")
    GroupPermission = apps.get_model("login", "GroupPermission")
    OrganizationPermission = apps.get_model("login", "OrganizationPermission")
    GroupMembership = apps.get_model("login", "GroupMembership")
    OrganizationMembership = apps.get_model("login", "OrganizationMembership")

    for ug in UserGroup.objects.all():
        # Reuse the auth.Group row the UserGroup already extends, so the
        # organization keeps its name and its primary key (Membership.group
        # and GroupPermission.holder end up pointing at auth.Group).
        org = Organization(
            group_ptr_id=ug.group_ptr_id,
            name=ug.name,
            description=ug.description,
            is_admin=ug.is_admin,
        )
        org.save_base(raw=True)
        # Copy permissions
        for gp in GroupPermission.objects.filter(holder=ug):
            OrganizationPermission.objects.get_or_create(
                holder=org,
                table=gp.table,
                level=gp.level,
            )

        # Copy memberships
        for gm in GroupMembership.objects.filter(group=ug):
            OrganizationMembership.objects.get_or_create(
                user=gm.user,
                organization=org,
                level=gm.level,
            )


def copy_organizations_to_groups(apps, schema_editor):
    UserGroup = apps.get_model("login", "UserGroup")
    Organization = apps.get_model("login", "Organization")
    GroupPermission = apps.get_model("login", "GroupPermission")
    OrganizationPermission = apps.get_model("login", "OrganizationPermission")
    GroupMembership = apps.get_model("login", "GroupMembership")
    OrganizationMembership = apps.get_model("login", "OrganizationMembership")

    for org in Organization.objects.all():
        # Mirror of the forward step: the UserGroup goes back onto the same
        # auth.Group row, so name and primary key survive the round trip.
        ug = UserGroup(
            group_ptr_id=org.group_ptr_id,
            name=org.name,
            description=org.description,
            is_admin=org.is_admin,
        )
        ug.save_base(raw=True)
        # Copy permissions
        for p in OrganizationPermission.objects.filter(holder=org):
            GroupPermission.objects.get_or_create(
                holder=ug,
                table=p.table,
                level=p.level,
            )

        # Copy memberships
        for m in OrganizationMembership.objects.filter(organization=org):
            GroupMembership.objects.get_or_create(
                user=m.user,
                group=ug,
                level=m.level,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0024_organization_alter_groupmembership_user_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_groups_to_organizations, copy_organizations_to_groups
        ),
    ]
