"""
SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0025_auto_20260305_1420"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grouppermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="grouppermission",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="grouppermission",
            name="table",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="group_ptr",
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
        migrations.DeleteModel(
            name="GroupPermission",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
    ]
