# Generated by Django 5.1.15 on 2026-03-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0025_auto_20260305_1420"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grouppermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="grouppermission",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="grouppermission",
            name="table",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="group_ptr",
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
        migrations.DeleteModel(
            name="GroupPermission",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
    ]
