"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0026_alter_grouppermission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="acronym",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="homepage",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
