# Generated by Django 3.2.18 on 2023-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_myuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='../'),
        ),
    ]
