# Generated by Django 5.1.15 on 2026-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0027_organization_acronym_organization_homepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="image",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Link to an image"
            ),
        ),
    ]
