"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0028_alter_organization_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationMembership",
            new_name="Membership",
        ),
    ]
