"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0029_rename_organizationmembership_membership"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="organization",
            new_name="group",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "group")},
        ),
    ]
