# Generated by Django 3.2.18 on 2023-03-20 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_alter_myuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
