# Generated by Django 3.2 on 2023-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_myuser_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
