# Generated by Django 5.1.15 on 2026-03-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataedit", "0045_alter_embargo_table"),
        ("login", "0031_alter_membership_group"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationPermission",
            new_name="GroupPermission",
        ),
    ]
