"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("login", "0032_rename_organizationpermission_grouppermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppermission",
            name="holder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_permissions",
                to="auth.group",
            ),
        ),
    ]
