"""
SPDX-FileCopyrightText: 2026 Hendrik Huyskens <https://github.com/henhuy> © Reiner Lemoine Institut

SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 5.1.15 on 2026-03-11 10:24

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models

import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("login", "0033_alter_grouppermission_holder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("acronym", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(default="")),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Link to an image",
                    ),
                ),
                ("homepage", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "grant_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "funding_agency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=100, null=True)),
                ("keywords", models.CharField(blank=True, max_length=250, null=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            bases=("auth.group", login.models.PermissionHolder),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
