# SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Bryan Lancien <https://github.com/bmlancien> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Eike Broda <https://github.com/ebroda>
# SPDX-FileCopyrightText: 2025 Johann Wagner <https://github.com/johannwagner>  © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Johann Wagner <https://github.com/johannwagner>  © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Martin Glauer <https://github.com/MGlauer> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Santosch Mutyala <https://github.com/smutyala1at>
# SPDX-FileCopyrightText: 2025 Tu Phan Ngoc <RL-INSTITUT\tuphan.ngoc@rli-nb-65.rl-institut.local> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Venkatesh Murugadas <venkatesh.murugadas@st.ovgu.de> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Christian Winger <https://github.com/wingechr> © Öko-Institut e.V.
# SPDX-FileCopyrightText: 2025 Daryna Barabanova <https://github.com/Darynarli> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Django settings for oeplatform project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pathlib import Path

try:
    from .securitysettings import *  # noqa
except ImportError:
    import logging
    import os

    logging.error("No securitysettings found. Triggerd in oeplatform/settings.py")
    SECRET_KEY = os.environ.get("SECRET_KEY", "0")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
    URL = os.environ.get("URL")
    DEBUG = os.environ.get("DEBUG", "True")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = (
    "django.contrib.sites",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sessions.backends.signed_cookies",
    "django_bootstrap5",
    "rest_framework",
    "rest_framework.authtoken",
    "django_vite",
    "modelview",
    "modelview.templatetags.modelview_extras",
    "login",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "base",
    "base.templatetags.base_tags",
    "widget_tweaks",
    "dataedit",
    "colorfield",
    "api",
    "ontology",
    "axes",
    "captcha",
    "django.contrib.postgres",
    "fontawesome_5",
    "django_better_admin_arrayfield",
    "oeo_viewer",
    "factsheet",
    "oeo_ext",
    "corsheaders",
    "owlready2",
    "compressor",
    "oekg",
)

MIDDLEWARE = (
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "axes.middleware.AxesMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "allauth.account.middleware.AccountMiddleware",
)

ROOT_URLCONF = "oeplatform.urls"

EXTERNAL_URLS = {
    "tutorials_index": "https://openenergyplatform.github.io/academy/",
    "tutorials_faq": "https://openenergyplatform.github.io/academy/questions/",
    "tutorials_api1": "https://openenergyplatform.github.io/academy/tutorials/01_api/01_api_download/",  # noqa E501
    "tutorials_api_upload": "https://openenergyplatform.github.io/academy/tutorials/01_api/02_api_upload/",  # noqa E501
    "tutorials_licenses": "https://openenergyplatform.github.io/academy/tutorials/metadata/tutorial_open-data-licenses/",  # noqa E501
    "tutorials_wizard": "https://openenergyplatform.github.io/academy/tutorials/99_other/wizard/",  # noqa E501
    "tutorials_create_database_conform_data": "https://openenergyplatform.github.io/academy/tutorials/99_other/database_data/",  # noqa E501
    "tutorials_oemetadata": "https://openenergyplatform.github.io/academy/tutorials/99_other/getting_started_with_OEMetadata/",  # noqa E501
    "tutorials_oemetabuilder": "https://openenergyplatform.github.io/academy/tutorials/99_other/oemetadata/",  # noqa E501
    "readthedocs": "https://openenergyplatform.github.io/oeplatform/oeplatform-code/web-api/oedb-rest-api/",  # noqa E501
    "mkdocs": "https://openenergyplatform.github.io/oeplatform/",
    "compendium": "https://openenergyplatform.github.io/organisation/",
    "tib_terminology_service": "https://terminology.tib.eu/ts/collections",
    "tib_ts_oeo": "https://terminology.tib.eu/ts/ontologies/oeo",
    "spdx_licenses": "https://spdx.github.io/license-list-data/",
    "oemetadata_key_description": "https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/oemetadata/latest/metadata_key_description.md",  # noqa E501
    "oeo_extended_github": "https://github.com/OpenEnergyPlatform/oeo-extended",  # noqa E501
    "oedatamodel": "https://github.com/OpenEnergyPlatform/oedatamodel",
    "ORKG": "https://academy.orkg.org/orkg-academy/main/index.html",
    "open_plan": "https://open-plan-tool.org/",
    "open_mastr": "https://open-mastr.readthedocs.io/en/latest/",
}

# Kept this separate for now to avoid messing with the other list ...
# TODO move to EXTERNAL_URLS if possible
DOCUMENTATION_LINKS = {
    "oeo_setup": "https://openenergyplatform.github.io/oeplatform/installation/guides/installation/#3-setup-the-openenergyontology-integration",  # noqa:E501
    "oeo_ext_setup": "https://openenergyplatform.github.io/oeplatform/installation/guides/installation/#62-setup-the-oeo-extended-app",  # noqa:E501
    "oemetabuilder": "https://openenergyplatform.github.io/oeplatform/oeplatform-code/features/metaBuilder/",  # noqa:E501
    "oekg_api": "https://openenergyplatform.github.io/oeplatform/oeplatform-code/web-api/oekg-api/",  # noqa:E501
}


def external_urls_context_processor(request):
    """Define hard coded external urls here.
    Use in templates like this: {{ EXTERNAL_URLS.<name_of_url> }}
    Also, you may want to add an icon indicating external links, e.g.
    """
    return {"EXTERNAL_URLS": EXTERNAL_URLS}


SITE_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "oeplatform.settings.external_urls_context_processor",
                "oeplatform.context_processors.allauth_settings",
            ]
        },
    }
]

CORS_ORIGIN_WHITELIST = ["http://localhost:3000", "http://127.0.0.1:3000"]

GRAPHENE = {"SCHEMA": "factsheet.schema.schema"}

WSGI_APPLICATION = "oeplatform.wsgi.application"

# from security settings
try:
    ONTOLOGY_FOLDER  # noqa F405
except NameError:
    ONTOLOGY_FOLDER = "/tmp"

# from security settings
try:
    BASE_DIR  # noqa F405
except NameError:
    BASE_DIR = ""

# from security settings
try:
    MEDIA_ROOT  # noqa F405
except NameError:
    MEDIA_ROOT = "/media"

try:
    ONTOLOGY_ROOT  # noqa F405
except NameError:
    if BASE_DIR:
        ONTOLOGY_ROOT = Path(BASE_DIR, ONTOLOGY_FOLDER)

if ONTOLOGY_ROOT:
    OPEN_ENERGY_ONTOLOGY_NAME = "oeo"
    OPEN_ENERGY_ONTOLOGY_FOLDER = Path(
        ONTOLOGY_ROOT, OPEN_ENERGY_ONTOLOGY_NAME  # noqa:F405
    )
    OPEN_ENERGY_ONTOLOGY_FULL_OWL_NAME = "oeo-full.owl"

if MEDIA_ROOT:
    OEO_EXT_PATH = Path(MEDIA_ROOT, "oeo_ext")
    OEO_EXT_NAME = "oeox"
    OEO_EXT_OWL_NAME = "oeo_ext.owl"
    OEO_EXT_OWL_PATH = OEO_EXT_PATH / OEO_EXT_OWL_NAME

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

AUTH_USER_MODEL = "login.myuser"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-url
LOGIN_URL = "account_login"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = "login:redirect"
# LOGIN_REDIRECT_URL = "/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    )
}

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
    # custom class extending Django ModelBackend for login with username OR email
    "login.backends.ModelBackendWithEmail",
    "allauth.account.auth_backends.AuthenticationBackend",
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

STATICFILES_FINDERS = {
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
}


# https://django-compressor.readthedocs.io/en/stable/settings.html
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_REBUILD_TIMEOUT = 0
COMPRESS_MTIME_DELAY = 0
COMPRESS_FILTERS = {
    # do not minify js, we do it with parcel
    # and it can create problems with react
    "js": [],
    # we minify with parcel, but we need to pass it
    # through CssAbsoluteFilter to resolve linked fonts
    "css": [
        "compressor.filters.css_default.CssAbsoluteFilter",
    ],
}

ACCOUNT_USER_MODEL_USERNAME_FIELD = "name"
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # requires ACCOUNT_EMAIL_REQUIRED = True
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_ADAPTER = "login.adapters.AccountAdapter"
# https://django-allauth.readthedocs.io/en/latest/forms.html
ACCOUNT_FORMS = {"signup": "login.forms.CreateUserForm"}
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_ALLOW_REGISTRATION = True
ACCOUNT_FORMS = {"signup": "login.forms.CreateUserForm"}
# ACCOUNT_SIGNUP_FORM_CLASS = {"login.forms.CreateUserForm"}
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True


# https://django-allauth.readthedocs.io/en/latest/configuration.html
SOCIALACCOUNT_ADAPTER = "login.adapters.SocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"
# https://django-allauth.readthedocs.io/en/latest/forms.html
# SOCIALACCOUNT_FORMS = {"signup": "login.forms.CreateUserForm"}
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# axes login throttling
AXES_ENABLED = not DEBUG
AXES_FAILURE_LIMIT = 5  # Number of allowed attempts
AXES_COOLOFF_TIME = 1  # Lockout period in hours
AXES_ONLY_USER_FAILURES = True  # Only track failures per user

CAPTCHA_IMAGE_SIZE = (150, 60)  # width, height in pixels
CAPTCHA_FONT_SIZE = 42

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}
