name: "databus-dev"
services:
  databus:
    env_file: ./serviceConfigs/databus/.env
    image: "dbpedia/databus:dev"
    ports:
      - 3000:3000 # HTTP:  Databus web UI
#      - 80:80       # ** uncomment if proxy enabled only** HTTP port of included proxy (caddy) necessary for Auto-HTTPS via ACME and HTTP->HTTPS redirect
#      - 443:4000    # ** uncomment if proxy enabled only** HTTPS: Databus web UI via caddy proxy
    environment:
      DATABUS_RESOURCE_BASE_URL: ${DATABUS_RESOURCE_BASE_URL}
      DATABUS_DATABASE_URL: "http://gstore:8080"
      LOOKUP_BASE_URL: "http://lookup:8082"
      METRICS_PORT: "3001"
      DATABUS_OIDC_ISSUER_BASE_URL: ${DATABUS_OIDC_ISSUER_BASE_URL}
      DATABUS_NAME: ${DATABUS_NAME}
      DATABUS_ABSTRACT: ${DATABUS_ABSTRACT}
      DATABUS_ORG_ICON: ${DATABUS_ORG_ICON}
      DATABUS_BANNER_COLOR: ${DATABUS_BANNER_COLOR}
      DATABUS_OIDC_CLIENT_ID: ${DATABUS_OIDC_CLIENT_ID}
      DATABUS_OIDC_SECRET: ${DATABUS_OIDC_SECRET}
      DATABUS_PRIVATE_MODE: ${DATABUS_PRIVATE_MODE} # Private mode will only show metadata for logged-in users
    volumes:
      - ./databus/data/dav/:/databus/server/dav/
      - ./databus/data/sqlite/:/databus/server/sqlite
      - ./databus/data/keypair/:/databus/server/keypair
  gstore:
    env_file: ./serviceConfigs/databus/.env
    image: "docker.io/dbpedia/gstore:dev"
    environment:
      STORAGE_USER: ${VIRTUOSO_USER}
      STORAGE_PASS:  ${VIRTUOSO_PASSWORD}
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
      # gstore now is preloading the context for localhost from a configured remote location
      # only needed for dev env with context at localhost
      DEFAULT_JSONLD_LOCALHOST_CONTEXT: http://localhost:3000/res/context.jsonld
      DEFAULT_JSONLD_LOCALHOST_CONTEXT_LOCATION: http://databus:3000/res/context.jsonld
    ports:
      - 3002:8080
    volumes:
      - ./databus/data/gstore/repo:/gstore/git
      - ./databus/data/gstore/logs:/gstore/logs
  virtuoso:
    env_file: ./serviceConfigs/databus/.env
    image: "docker.io/openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: ${DATABUS_RESOURCE_BASE_URL}
    ports:
      - 3003:8890
    volumes:
      - ./databus/data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh"
  lookup:
    env_file: ./serviceConfigs/databus/.env
    image: dbpedia/lookup:dev
    container_name: databus_devenv_lookup
    volumes:
      - ./databus/data/index/:/index
      - ./serviceConfigs/databus/lookup-config.yaml:/resources/config.yml
