"""drop table meta search

Revision ID: 4a999e7a3f93
Revises: 3c2369dfcc55
Create Date: 2025-10-17 16:23:49.731335

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4a999e7a3f93"
down_revision = "3c2369dfcc55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meta_search", schema="public")
    op.alter_column(
        "_edit_base",
        "_message",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        nullable=False,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "_edit_base",
        "_message",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.create_table(
        "meta_search",
        sa.Column("schema", sa.String(length=100), nullable=False),
        sa.Column("table", sa.String(length=100), nullable=False),
        sa.Column("comment", postgresql.TSVECTOR(), nullable=True),
        sa.PrimaryKeyConstraint("schema", "table"),
        schema="public",
    )
    # ### end Alembic commands ###
