# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('html', models.TextField()),
                ('markdown', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
