# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.CharField(blank=True, choices=[('io', 'I/O'), ('intro', 'Introduction')], max_length=15),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True),
        ),
    ]
