# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20191212_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginners'), (2, 'Intermediates'), (3, 'Advanced')], null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='markdown',
            field=martor.models.MartorField(),
        ),
    ]
