# Generated by Django 3.2.7 on 2022-09-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
