# Generated by Django 3.2.7 on 2022-11-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsheet',
            name='factsheetData',
            field=models.JSONField(default={}),
        ),
    ]
