# Generated by Django 3.2.7 on 2023-07-11 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfOEKG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triple_subject', models.TextField()),
                ('triple_predicate', models.TextField()),
                ('triple_object', models.TextField()),
                ('type_of_action', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Factsheet',
        ),
    ]
