# Generated by Django 3.2.19 on 2023-09-29 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0002_auto_20230711_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofoekg',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
