# Generated by Django 3.2.7 on 2022-09-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0002_auto_20220906_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uri', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='FundingSourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uri', models.URLField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='factsheetmodel',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factsheet.fundingsourcemodel'),
        ),
    ]
