# Generated by Django 3.2.7 on 2023-11-01 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factsheet", "0003_alter_historyofoekg_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="OEKG_Modifications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_state", models.JSONField()),
                ("new_state", models.JSONField()),
                ("user", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name="HistoryOfOEKG",
        ),
    ]
