# Generated by Django 3.2.7 on 2023-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0003_alter_factsheet_factsheetdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheet',
            name='acronym',
            field=models.CharField(default='acronym', max_length=100),
        ),
        migrations.AlterField(
            model_name='factsheet',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
