# SPDX-FileCopyrightText: 2025 Adel Memariani <adel.memariani@ovgu.de>
# SPDX-FileCopyrightText: 2025 Jonas Huber <jonas.huber@rl-institut.de>
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.7 on 2023-11-02 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("factsheet", "0004_auto_20231101_1613"),
    ]

    operations = [
        migrations.AddField(
            model_name="oekg_modifications",
            name="bundle_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
        ),
        migrations.AlterField(
            model_name="oekg_modifications",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
