# SPDX-FileCopyrightText: 2025 Adel Memariani <adel.memariani@ovgu.de>
# SPDX-FileCopyrightText: 2025 Jonas Huber <jonas.huber@rl-institut.de>
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.7 on 2023-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factsheet", "0005_auto_20231102_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oekg_modifications",
            name="bundle_id",
            field=models.CharField(default="none", max_length=400),
        ),
    ]
