"""
SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
SPDX-License-Identifier: AGPL-3.0-or-later
"""  # noqa: 501

# Generated by Django 3.2.7 on 2023-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factsheet", "0005_auto_20231102_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oekg_modifications",
            name="bundle_id",
            field=models.CharField(default="none", max_length=400),
        ),
    ]
