# Generated by Django 3.2.7 on 2023-11-02 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factsheet', '0006_alter_oekg_modifications_bundle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oekg_modifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
