# Generated by Django 3.2.7 on 2023-11-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0008_alter_oekg_modifications_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oekg_modifications',
            old_name='user',
            new_name='user_id',
        ),
    ]
