# SPDX-FileCopyrightText: 2025 Adel Memariani <https://github.com/adelmemariani> © Otto-von-Guericke-Universität Magdeburg
# SPDX-FileCopyrightText: 2025 Jonas Huber <https://github.com/jh-RLI> © Reiner Lemoine Institut
#
# SPDX-License-Identifier: MIT

# Generated by Django 3.2.7 on 2023-11-02 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("factsheet", "0008_alter_oekg_modifications_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oekg_modifications",
            old_name="user",
            new_name="user_id",
        ),
    ]
