# Generated by Django 3.2.23 on 2024-02-26 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0011_scenariobundleaccesscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=400)),
                ('timeout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=400)),
            ],
        ),
    ]
